<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlbionApp.Application\AlbionApp.Application.csproj" />
    <ProjectReference Include="..\..\LibSolutions\LibServiceLifecycle\LibServiceLifecycle.csproj" />
    <ProjectReference Include="..\..\LibSolutions\LibAlbionData\LibAlbionData.csproj" />
    <ProjectReference Include="..\..\LibSolutions\LibEvents\LibEvents.csproj" />
    <ProjectReference Include="..\..\LibSolutions\LibAlbionGame\LibAlbionGame.csproj" />
  </ItemGroup>


</Project>
