<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlbionApp.Domain\AlbionApp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Crafting\" />
    <Folder Include="UseCases\SearchItems\" />
  </ItemGroup>

</Project>
